port:  5000
markdown: kramdown
name: "My Reps"
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/Chicago
description: "Enter your physical address to find your elected state representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyAVQrWzBeHiKaOiNwkEyLkxDV8-jUbTmTw
